welcome_page_title:
  other: Willkommen auf der {page}
  
welcome_page_subtitle:
  other: Slack ist eine Messaging-App für Teams.

about_page_title:
  other: Hallo!

about_page_back_button:
  other: Weiterlesen
