welcome_page_title:
  other: Bem vindo a {page}
  
welcome_page_subtitle:
  other: O Slack é um aplicativo de mensagens para equipes.

about_page_title:
  other: Olá!

about_page_back_button:
  other: Leia mais
