welcome_page_title:
  other: Witamy na {page}
  
welcome_page_subtitle:
  other: Slack to aplikacja do przesyłania wiadomości dla zespołów.

about_page_title:
  other: Cześć!

about_page_back_button:
  other: Czytaj więcej
